project:
  type: book
  output-dir: docs

book:
  title: "Wiki"
  author: "Anderson A. Anderson"
  date: today
  chapters:
    - index.qmd
    - content/content.qmd
    - content/references.qmd

bibliography: content/references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  html:
    theme:
      light: flatly
      dark: darkly
    number-sections: false
